import { PrismaClient } from '@prisma/client';
const db=new PrismaClient();
const date=(n,h=8)=>{const d=new Date();d.setHours(h,0,0,0);d.setDate(d.getDate()+n);return d};
const catalog=[
['Udang Vaname Segar','Udang',92000,25],['Udang Windu Jumbo','Udang',165000,14],['Udang Galah','Udang',185000,10],['Udang Kupas Beku','Udang',118000,18],['Udang Rebon Segar','Udang',48000,22],
['Ikan Nila Merah','Ikan air tawar',42000,32],['Ikan Gurame','Ikan air tawar',78000,17],['Ikan Lele','Ikan air tawar',31000,40],['Ikan Patin','Ikan air tawar',39000,28],['Ikan Mas','Ikan air tawar',46000,24],
['Ikan Bandeng','Ikan laut',44000,26],['Ikan Kakap Merah','Ikan laut',112000,13],['Ikan Kerapu','Ikan laut',135000,9],['Ikan Tongkol','Ikan laut',43000,30],['Ikan Kembung','Ikan laut',52000,27],
['Ikan Cakalang','Ikan laut',58000,20],['Cumi-Cumi Segar','Hasil laut',88000,16],['Kepiting Bakau','Hasil laut',155000,11],['Kerang Hijau','Hasil laut',36000,35],['Fillet Dori Beku','Ikan beku',67000,21]];
const vendorList=[['Tambak Bahari Jaya','Muara Angke'],['Nelayan Laut Biru','Pelabuhan Ratu'],['Mina Sejahtera','Bogor'],['Tambak Vaname Makmur','Karawang'],['Hasil Laut Nusantara','Muara Baru'],['Kolam Ikan Berkah','Parung'],['Samudra Segar Abadi','Cirebon'],['Pesisir Jaya Seafood','Indramayu']];
const names=['Budi Santoso','Siti Rahma','Andi Wijaya','Dewi Lestari','Rizky Pratama','Nur Aisyah','Agus Setiawan','Maya Putri','Fajar Hidayat','Rina Marlina','Dedi Kurniawan','Lina Oktavia','Hendra Gunawan','Yuni Kartika','Bayu Saputra','Nadia Permata','Eko Susanto','Fitri Handayani','Arif Maulana','Wulan Sari'];
async function main(){
 const vendors=[];for(let i=0;i<vendorList.length;i++){const [name,address]=vendorList[i];vendors.push(await db.vendor.findFirst({where:{name}})??await db.vendor.create({data:{name,address,phone:`08123456010${i+1}`,paymentTerms:7+(i%4)*7,notes:'Pemasok contoh dengan jadwal pengiriman rutin.'}}))}
 const products=[];for(const [name,category,price,stock] of catalog)products.push(await db.product.findFirst({where:{name}})??await db.product.create({data:{name,category,unit:name==='Fillet Dori Beku'?'pak':'kg',price,stock,isActive:true,description:`${name} pilihan yang segar, berkualitas, dan siap diolah.`}}));
 for(let i=0;i<20;i++){const invoiceNumber=`DEMO-BELI-${String(i+1).padStart(3,'0')}`;if(await db.purchase.findUnique({where:{invoiceNumber}}))continue;const p=products[i],v=vendors[i%8],qty=catalog[i][3]+8,sell=catalog[i][2],buy=Math.round(sell*(.67+(i%4)*.025)),total=qty*buy,pay=i%3===0?'TEMPO':i%3===1?'TRANSFER':'TUNAI',paid=pay==='TEMPO'?(i%2?Math.round(total*.35):0):total;const purchase=await db.purchase.create({data:{invoiceNumber,date:date(-30+i),vendorId:v.id,paymentType:pay,dueDate:pay==='TEMPO'?date(-9+i):null,totalAmount:total,paidAmount:paid,notes:`Pasokan rutin ${p.name}.`,items:{create:{productId:p.id,quantity:qty,buyPrice:buy,sellPrice:sell,total,ownership:i%7===0?'KONSINYASI':'BELI_PUTUS'}}},include:{items:true}});const batch=await db.stockBatch.create({data:{code:`DEMO-STOK-${String(i+1).padStart(3,'0')}`,receivedAt:purchase.date,productId:p.id,purchaseItemId:purchase.items[0].id,initialQty:qty,remainingQty:catalog[i][3],buyPrice:buy,sellPrice:sell,ownership:i%7===0?'KONSINYASI':'BELI_PUTUS'}});await db.stockMovement.createMany({data:[{date:purchase.date,productId:p.id,batchId:batch.id,type:'PEMBELIAN',quantity:qty,unitCost:buy,referenceId:invoiceNumber,description:`Stok masuk dari ${v.name}`},{date:date(-12+i),productId:p.id,batchId:batch.id,type:'PENJUALAN',quantity:8,unitCost:buy,referenceId:`DEMO-PAKAI-${i+1}`,description:'Stok terjual melalui pesanan contoh'}]});if(paid>0&&pay==='TEMPO')await db.vendorPayment.create({data:{vendorId:v.id,purchaseId:purchase.id,date:date(-5+i),amount:paid,method:'TRANSFER',notes:'Pembayaran sebagian pembelian contoh'}})}
 for(let i=0;i<20;i++){
  const customerPhone=`08129876${1000+i}`;
  if(await db.order.findFirst({where:{customerPhone}}))continue;
  const p=products[i],qty=i%4===0?2:1,price=Number(p.price),hpp=Math.round(price*.7)*qty,total=price*qty,status=['BARU','DIPROSES','SELESAI','SELESAI','DIBATALKAN'][i%5],createdAt=date(-19+i,9+i%8);
  const order=await db.order.create({data:{orderNumber:`TMP-SEED-${i}-${Date.now()}`,customerName:names[i],customerPhone,address:`Jalan Melati No. ${i+10}, Kota Bogor`,paymentType:i%4===0?'TUNAI':'TRANSFER',totalAmount:total,hppAmount:hpp,grossProfit:status==='DIBATALKAN'?0:total-hpp,status,notes:i%3===0?'Mohon dibersihkan sebelum dikirim.':'Hubungi pelanggan sebelum pengiriman.',createdAt,completedAt:status==='SELESAI'?date(-18+i,16):null,items:{create:{productId:p.id,quantity:qty,price,hpp,total}}}});
  await db.order.update({where:{id:order.id},data:{orderNumber:`ORD${order.id}-${createdAt.getMonth()+1}-${createdAt.getDate()}-${createdAt.getFullYear()}`}});
 }
 const cash=[['MASUK','Penjualan toko',275000],['KELUAR','Listrik',450000],['KELUAR','Es batu',85000],['KELUAR','Transportasi',175000],['MASUK','Penjualan langsung',390000],['KELUAR','Kemasan',125000],['KELUAR','Kebersihan',95000],['MASUK','Penjualan toko',520000],['KELUAR','Upah harian',300000],['KELUAR','Air',180000],['MASUK','Penjualan rumah makan',465000],['KELUAR','Perawatan alat',240000]];for(let i=0;i<cash.length;i++){const referenceId=`DEMO-KAS-${i+1}`;if(!await db.cashTransaction.findFirst({where:{referenceId}}))await db.cashTransaction.create({data:{date:date(-15+i),type:cash[i][0],category:cash[i][1],amount:cash[i][2],description:`Transaksi contoh ${cash[i][1].toLowerCase()}.`,referenceId}})}
 const caps=[['SETORAN',25000000,'Modal awal'],['TAMBAHAN',5000000,'Lemari pendingin'],['PRIVE',1500000,'Kebutuhan pemilik'],['TAMBAHAN',3000000,'Belanja stok'],['PRIVE',750000,'Pengambilan mingguan']];for(let i=0;i<caps.length;i++){const description=`[CONTOH ${i+1}] ${caps[i][2]}`;if(!await db.capitalTransaction.findFirst({where:{description}}))await db.capitalTransaction.create({data:{date:date(-45+i*8),type:caps[i][0],amount:caps[i][1],description}})}
 for(let i=14;i>=1;i--){const d=date(-i);d.setHours(0,0,0,0);const sales=850000+i%5*175000,hpp=Math.round(sales*.7),expense=75000+i%3*25000;await db.dailyClosing.upsert({where:{date:d},update:{},create:{date:d,purchaseAmount:600000+i%4*125000,salesAmount:sales,hppAmount:hpp,expenseAmount:expense,grossProfit:sales-hpp,netProfit:sales-hpp-expense,remainingStock:320+i*3,notes:'Penutupan harian data contoh.',closedAt:date(-i,21)}})}
 if(!await db.auditLog.findFirst({where:{entityId:'DEMO-2026'}}))await db.auditLog.create({data:{action:'SEED_DATA_CONTOH',entity:'Semua halaman',entityId:'DEMO-2026',details:'Data contoh udang dan ikan berhasil ditambahkan.'}});console.log('Selesai: 20 produk, 20 pembelian, 20 pesanan, dan data semua halaman.')}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect());
